data:
  dataset: pascal_voc
  img_cols: same
  img_rows: same
  split: '0.7'
  train_split: train_aug
model:
  arch: nas-unet
searching:
  alpha_begin: 10
  arch_optimizer: null
  batch_size: null
  depth: 4
  double_down_channel: false
  epoch: null
  gpu: true
  grad_clip: 5
  init_channels: 16
  loss: null
  max_patience: 40
  meta_node_num: 3
  model_optimizer:
    lr: 0.001
    name: adabound
    weight_decay: 0.0005
  multi_gpus: true
  n_workers: 2
  report_freq: 20
  resume: null
  sharing_normal: true
  train_portion: null
training:
  backbone: null
  batch_size: null
  depth: 5
  double_down_channel: false
  epoch: null
  geno_type: null
  grad_clip: 3
  init_channels: 48
  loss: null
  lr_schedule:
    max_iter: 100
    name: poly_lr
  max_patience: 20
  model_optimizer: null
  multi_gpus: false
  n_workers: 10
  report_freq: 50
  resume: ../logs/nasunet/train/pascal_voc/20210307-200013/model_best.pth.tar
  val_batch_size: null
